<style>

    @media print {
        @page {
            size: A4;
            margin: 0;
        }
        .header{
            display:none !important;
        }
        .notification-global{
            display:none !important;
        }
        .inventory-nav-bar{
            display:none !important;
        }
        #inventory-title{
            display:none !important;
        }
        .footer{
            display:none !important;
        }
        .button-print{
            display:none !important;
        }
        .button-printpdf{
            display:none !important;
        }

}

</style>
<?php $params = $this->getRequest()->getParams(); ?>
<?php if(isset($params['barcodeId']) && $params['barcodeId']){
	$barcodeIds = array($params['barcodeId']);
}else if(isset($params['barcodeIds']) && $params['barcodeIds']){
	$barcodeIds = explode(',', $params['barcodeIds']);
}

if(isset($params['data']) && $params['data'] ){
    $data = $params['data'];
}
$purchaseorderProducts = array();
parse_str(urldecode($data), $purchaseorderProducts);

?>

<?php $type = $params['type'];?>
<?php $qty = $params['number_of_barcode'];?>
<?php
        $printingFormat = $params['barcode_template'];
        if($printingFormat == 5 ){
            $pageWidth= 3.94;
        }else{
            $pageWidth = 4.7;
        }

    function show( $abc ){
        if(strlen($abc) == 23 ){
         return  substr($abc,0,23);
        }
        if (strlen($abc) < 23) {
         return  $abc;
        }
        if (strlen($abc) > 23){
         $abc = substr($abc,0,20);
         return $abc." ...";
        }
    }
?>
<?php $template = $params['barcode_template'];?>
<?php
        $customize = 0;
        $heightImage = 0;
        if(isset($params['customize']) && $params['customize']){
            $customize = 1;
            $heightImage = $params['heigth_barcode'];
        }
?>
<div style-="width:100%; float:left;" class="button-print">
<button style="padding: 5px; width: 90px; font-size: 16px; margin: 10px;" onclick="printbarcode()" type="button"><?php echo $this->__('Print') ?></button>
</div>


<!--Edit by alan - print barcode -->

<?php if(empty($data)){?>
<?php $dataTemplate=Mage::helper('inventorybarcode')->getDataTemplateBarcode($template);?>
<div id="mydiv" style="width:<?php echo $dataTemplate['page_width'].$dataTemplate['barcode_unit'];?>; float:left; margin:<?php echo $dataTemplate['top_margin'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['right_margin'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['bottom_margin'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['left_margin'].$dataTemplate['barcode_unit'];?>">
    <?php foreach($barcodeIds as $barcodeId){?>
            
            <?php $barcode = Mage::getModel('inventorybarcode/barcode')->load($barcodeId);?>
            <?php for($i = 0; $i<$qty; $i++){?>
                
                <?php if($dataTemplate && $template!=5 ){?>
                    <?php $product = Mage::getModel('catalog/product')->load($barcode->getProductEntityId());?>
                <table style="width:<?php echo $dataTemplate['page_width'].$dataTemplate['barcode_unit'];?>; height:<?php echo $dataTemplate['page_height'].$dataTemplate['barcode_unit'];?>; text-align: center; ">
                        <tr>
                            <?php for($j=0;$j<$dataTemplate['barcode_per_row'] ;$j++){  ?>
                                <td align ="center" style="width:35mm; height:22mm; padding:<?php echo $dataTemplate['horizontal_distance'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['veltical_distantce'].$dataTemplate['barcode_unit'];?>">
                                    
                                    
                                        <?php if($dataTemplate['productname_show']=='1'){?>
                                            <span style=" width:100%;float: left; font-size: 9px; text-align: center; "><?php echo $product->getName()?></span>
                                        <?php }?>
                                        <?php if($dataTemplate['sku_show']=='1'){?>
                                            <span style=" width:100%;float: left; font-size: 9px; text-align: center; "><?php echo $product->getSku() ?></span>
                                        <?php }?>
                                        <?php if($dataTemplate['price_show']=='1'){?>
                                            <span style=" width:100%;float: left; font-size: 12px; text-align: center;"><?php echo Mage::helper('core')->currency($product->getPrice())?></span>
                                        <?php }?>
                                        <img width="140" height="60" name="barcode_images" src="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/inb_printbarcode/getimage/',array('type' => $type, 'text' => $barcode->getBarcode(), 'customize' => $customize, 'heigth_barcode' => $heightImage, 'font_size' => 10)); ?>" />
                                    

                                </td>
                                        
                            <?php }?>

                        </tr>
                </table>
            <?php }?>
               
                <?php if($dataTemplate && $template==5){?>
                        <div style="display: inline-block; float:left; margin-left:35px; ">
                            <table style=" width:<?php echo $dataTemplate['page_width'].$dataTemplate['barcode_unit'];?>; height:<?php echo $dataTemplate['page_height'].$dataTemplate['barcode_unit'];?>; line-height:0.4; margin:<?php echo $dataTemplate['horizontal_distance'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['veltical_distantce'].$dataTemplate['barcode_unit'];?> " >
                                <tr>
                                    <td align="center" style="width:26mm; height:14mm;">
                                        <?php $product = Mage::getModel('catalog/product')->load($barcode->getProductEntityId());?>
                                        <?php if($dataTemplate['productname_show']=='1'){?>
                                            <span style="float: left; font-size: 8px; text-align: left; margin-left:10px;margin-top:2px;  "><?php echo show($product->getName())?></span></br>
                                        <?php }?>
                                        <?php if($dataTemplate['sku_show']=='1'){?>
                                            <span style="float: left; font-size: 8px; text-align: left; margin-left:10px;margin-top:2px;"><?php echo show($product->getSku())?></span></br>
                                        <?php }?>
                                        <?php if($dataTemplate['price_show']=='1'){?>
                                            <span style="float: left; font-size:10px; text-align: left; margin-left:10px;margin-top:4px; "><?php echo Mage::helper('core')->currency($product->getPrice())?></span>
                                        <?php }?>
                                    </td>
                                    <td align="center" style="width:22mm; height:14mm;">
                                       <img style=" margin-top: 15px;" width="100" height="40" name="barcode_images" src="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/inb_printbarcode/getimage/',array('type' => $type, 'text' => $barcode->getBarcode(), 'customize' => $customize, 'heigth_barcode' => $heightImage, 'font_size' => 10)); ?>" />
                                    </td>
                                    <td></td>
                                </tr>
                            </table>
                        </div>
                <?php }?>

            <?php }?>
    
    <?php }?>
</div>
<?php } ?>


<?php if($data): ?>
<?php $dataTemplate=Mage::helper('inventorybarcode')->getDataTemplateBarcode($template);?>
<div id="mydiv" style="width:<?php echo $dataTemplate['page_width'].$dataTemplate['barcode_unit'];?>; float:left; margin:<?php echo $dataTemplate['top_margin'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['right_margin'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['bottom_margin'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['left_margin'].$dataTemplate['barcode_unit'];?>">
    <?php foreach($purchaseorderProducts as $pId => $enCoded):?>
        <div style="width: 100%; float:left;">
            <?php $barcode = Mage::getModel('inventorybarcode/barcode')->load($pId);
                parse_str(base64_decode($enCoded), $codeArr);
                                   foreach($codeArr as $key => $qtyfor){
                                   }
                                   
            ?>

                <?php if($dataTemplate && $template!=5):?>
                    <?php $product = Mage::getModel('catalog/product')->load($barcode->getProductEntityId());?>
                <table style="width:<?php echo $dataTemplate['page_width'].$dataTemplate['barcode_unit'];?>; height:<?php echo $dataTemplate['page_height'].$dataTemplate['barcode_unit'];?>; text-align: center; ">
                       <tr>
                           <?php for($i = 0; $i<$qtyfor; $i++):?>
                               <?php if( ($i > 0) && ($i % $dataTemplate['barcode_per_row'] == 0) ): ?>
                                   </tr></table>
                                    <table style="width:<?php echo $dataTemplate['page_width'].$dataTemplate['barcode_unit'];?>; height:<?php echo $dataTemplate['page_height'].$dataTemplate['barcode_unit'];?>; text-align: center; "><tr>
                                <?php endif; ?>
                        <td align ="center" style="width:35mm; height:22mm; padding:<?php echo $dataTemplate['horizontal_distance'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['veltical_distantce'].$dataTemplate['barcode_unit'];?>">
                  
                            <?php if($dataTemplate['productname_show']=='1') {?>
                                <span style="float: left; font-size: 9px; text-align: center; width: 100%"><?php echo $product->getName()?></span>
                            <?php }?>
                                
                            <?php if($dataTemplate['sku_show']=='1') {?>
                                <span style="float: left; font-size: 9px; text-align: center; width: 100%"><?php echo $product->getSku() ?></span>
                            <?php }?>
                                
                            <?php if($dataTemplate['price_show']=='1') {?>
                                <span style="float: left; font-size: 12px; text-align: center; width: 100%"><?php echo Mage::helper('core')->currency($product->getPrice())?></span>
                            <?php }?>
                                <img width="140" height="60" name="barcode_images" src="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/inb_printbarcode/getimage/',array('type' => $type, 'text' => $barcode->getBarcode(), 'customize' => $customize, 'heigth_barcode' => $heightImage, 'font_size' => 10)); ?>" /></td>
                                    <?php endfor; ?>
                                    <?php if ($qtyfor % $dataTemplate['barcode_per_row'] != 0) { ?>
                                        <?php 
                                            $qtybarcode = $qtyfor % $dataTemplate['barcode_per_row'];
                                            $qtyShow = $dataTemplate['barcode_per_row']-$qtybarcode;
                                            for($j=0;$j<$qtyShow; $j++){
                                        ?>
                                            <td align ="left" style="width:35mm; height:22mm; padding:<?php echo $dataTemplate['horizontal_distance'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['veltical_distantce'].$dataTemplate['barcode_unit'];?>">
                                        <?php }?>
                                    <?php }; ?>
                        </tr>
                       </table>
                <?php endif;?>

                <?php if($dataTemplate && $template==5):?>
                        <div style="display: inline-block; float:left; margin-left:35px; ">
                            <table style=" width:<?php echo $dataTemplate['page_width'].$dataTemplate['barcode_unit'];?>; height:<?php echo $dataTemplate['page_height'].$dataTemplate['barcode_unit'];?>; line-height:0.4; margin:<?php echo $dataTemplate['horizontal_distance'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['veltical_distantce'].$dataTemplate['barcode_unit'];?> " >
                                <tr>
                                    <?php for($k = 0; $k<$qtyfor; $k++):?>
                                    </tr></table>
                                        <table style=" width:<?php echo $dataTemplate['page_width'].$dataTemplate['barcode_unit'];?>; height:<?php echo $dataTemplate['page_height'].$dataTemplate['barcode_unit'];?>; ; line-height:0.4; margin:<?php echo $dataTemplate['horizontal_distance'].$dataTemplate['barcode_unit'];?> <?php echo $dataTemplate['veltical_distantce'].$dataTemplate['barcode_unit'];?> " ><tr>
                                        <td align="center" style="width:26mm; height:14mm;">
                                            <?php $product = Mage::getModel('catalog/product')->load($barcode->getProductEntityId());?>
                                            <?php if($dataTemplate['productname_show']=='1') {?>
                                                <span style="float: left; font-size: 8px; text-align: left; margin-left:10px;margin-top:2px;  "><?php echo show($product->getName())?></span></br>
                                            <?php }?>
                                            <?php if($dataTemplate['sku_show']=='1') {?>
                                                <span style="float: left; font-size: 8px; text-align: left; margin-left:10px;margin-top:2px;"><?php echo show($product->getSku())?></span></br>
                                            <?php }?>
                                            <?php if($dataTemplate['price_show']=='1') {?>
                                                <span style="float: left; font-size:10px; text-align: left; margin-left:10px;margin-top:4px; "><?php echo Mage::helper('core')->currency($product->getPrice())?></span>
                                            <?php }?>
                                        </td>
                                        <td align="center" style="width:22mm; height:14mm;">
                                           <img style=" margin-top: 15px;" width="100" height="40" name="barcode_images" src="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/inb_printbarcode/getimage/',array('type' => $type, 'text' => $barcode->getBarcode(), 'customize' => $customize, 'heigth_barcode' => $heightImage, 'font_size' => 10)); ?>" />
                                        </td>
                                        <td></td>
                                    <?php endfor; ?>    
                                </tr>
                            </table>
                        </div>
                <?php endif;?>

        </div>
    <?php endforeach;?>
</div>
<?php endif; ?>

<!--end Edit by alan - print barcode -->

<script type="text/javascript">
    function printbarcode(){
        window.print();
    }


</script>

